# Generated by Django 4.1.5 on 2023-01-27 10:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("app_jana_sergienko", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="bdSave",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
