# Generated by Django 4.1.5 on 2023-01-27 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_jana_sergienko", "0002_contact_bdsave_alter_contact_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="bdSave",
        ),
    ]
