# Generated by Django 4.1.7 on 2023-02-20 07:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("app_jana_sergienko", "0005_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["name", "-birthday", "pk"]},
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="contacts_search",
            new_name="search_text",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="age",
        ),
        migrations.AddField(
            model_name="contact",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="indexed",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="contacts",
                to="app_jana_sergienko.tag",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="search_tags",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="app_jana_sergienko.tag"
            ),
        ),
    ]
