# Generated by Django 4.1.7 on 2023-02-20 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_jana_sergienko", "0006_tag_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["name", "age", "pk"]},
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="birthday",
            new_name="age",
        ),
    ]
